# Generated by Django 3.0.4 on 2020-05-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Frutas y verduras', 'Frutas y verduras'), ('Licores', 'Licores'), ('Cuidado personal', 'Cuidado personal'), ('Bebidas', 'Bebidas'), ('Lacteos', 'Lacteos'), ('Snacks', 'Snacks'), ('Hogar', 'Hogar'), ('Panaderia', 'Panaderia'), ('Despensa', 'Despensa'), ('Congelados', 'Congelados'), ('Pastas y granos', 'Pastas y granos'), ('Pollo, carne, pescado', 'Pollo, carne, pescado'), ('Mascotas', 'Mascotas'), ('Farmacia', 'Farmacia'), ('Otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponibilidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
